### ISSUE TITLE
Performance Test Script missing from repo: examples/provisioner/general-purpose-azure-smallnodes.yaml

### ISSUE THREAD

**Issue by johndohoneyjr** [Azure/karpenter#19]
### Version

__Karpenter Version:__ v0.0.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

FIle: examples/provisioner/general-purpose-azure-smallnodes.yaml is missing

### Actual Behavior

 make az-perftest100
hack/azure/perftest.sh 100
+ '[' -z 100 ']'
+ replicas=100
+ FMT=+%Y-%m-%dT%H-%M-%SZ
++ date +%Y-%m-%dT%H-%M-%SZ
+ START=2023-11-09T00-18-16Z
++ date --iso-8601=seconds
+ STARTKUBECTL=2023-11-09T00:18:16+00:00
+ mkdir -p logs
+ exec
+ exec
++ tee -i logs/az-perftest-2023-11-09T00-18-16Z-100.log
+ logk=logs/az-perftest-2023-11-09T00-18-16Z-100-karpenter.log
+ kubectl apply -f examples/provisioner/general-purpose-azure-smallnodes.yaml
error: the path "examples/provisioner/general-purpose-azure-smallnodes.yaml" does not exist
make: *** [Makefile-az.mk:212: az-perftest100] Error 1

### Steps to Reproduce the Problem

 make az-perftest100

### Resource Specs and Logs

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Thanks for sharing, there is a couple of references to our provisioners that did not get cleaned up. Also in Makefile.az for gpu provisioning, the readme, and a couple of other places. 


Also note those perf scripts dont run in macos, and have room for improvement. Let me clean those up!
