### ISSUE TITLE
Karpenter querying EC2Metadata API ?

### ISSUE THREAD

**Issue by ben5556** [Azure/karpenter#46]
### Version

__Karpenter Version:__ v0.29.2

__Kubernetes Version:__ v1.26.10

### Expected Behavior

Expected to Query Azure metadata instance API ?

### Actual Behavior

Seeing a request made to AWS EC2 API based on logs

```
{"level":"DEBUG","time":"2023-11-24T05:25:54.311Z","logger":"controller","message":"loaded log configuration from file \"/etc/karpenter/logging/zap-logger-config\"","commit":"1072d3b"}
{"level":"DEBUG","time":"2023-11-24T05:25:54.311Z","logger":"controller","message":"discovered karpenter version","commit":"1072d3b","version":"v0.32.1"}
{"level":"DEBUG","time":"2023-11-24T05:25:56.834Z","logger":"controller","message":"retrieving region from IMDS","commit":"1072d3b"}
panic: failed to get region from metadata server: EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: 400 Bad Request: Bad Request
	status code: 400, request id: 
caused by: EC2MetadataError: failed to make EC2Metadata request
<?xml version="1.0" encoding="utf-8"?>
<Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Code>InvalidHttpVerb</Code>
    <Message>The HTTP verb specified was not recognized by the server.</Message>
    <Details>'PUT' is not a supported verb.</Details>
</Error>
	status code: 400, request id: 

goroutine 1 [running]:
github.com/samber/lo.must({0x2736f40, 0xc0004d7580}, {0xc000a7fc60, 0x1, 0x1})
	github.com/samber/lo@v1.38.1/errors.go:51 +0x1c5
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.38.1/errors.go:65
github.com/aws/karpenter/pkg/operator.NewOperator({0x308db90, 0xc0009cfce0}, 0xc0009ab7a0)
	github.com/aws/karpenter/pkg/operator/operator.go:104 +0x314
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:33 +0x2a
```

### Steps to Reproduce the Problem

Install the version of Karpenter on ASK cluster

### Resource Specs and Logs

Attached error log entry above

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Hey ben, 

I believe you are looking to report an issue for [aws/karpenter](https://github.com/aws/karpenter).  

You can do so here: https://github.com/aws/karpenter/issues

**Comment by Bryce-Soghigian** [comment]
Hey ben, 

I believe you are looking to report an issue for [aws/karpenter](https://github.com/aws/karpenter).  

You can do so here: https://github.com/aws/karpenter/issues

**Comment by ben5556** [comment]
@Bryce-Soghigian I installed the helm chart from this Github repository on Azure AKS cluster and karpenter failed to start due to the above error. I thought the helm chart in this repository is for deploying on AKS clusters ? Please correct me if I am wrong.

**Comment by Bryce-Soghigian** [comment]
@ben5556  im sorry, the chart in our repo hasn't been prepared fully for public consumption just yet. Im sorry about the confusion here! 

Currently the easiest way to get a self hosted version of karpenter running on your cluster is to run `make az-all`(See more info in the readme of the project). 

We are preparing the managed offering for launch, and will have docs with a more official recommendation soon.

**Comment by ben5556** [comment]
Thanks @Bryce-Soghigian

**Comment by Bryce-Soghigian** [comment]
Of course Ben Please post more issues if you need additional support!
