### ISSUE TITLE
Can karpenter on AKS use Azure network plugin instead of Cilium ?

### ISSUE THREAD

**Issue by ben5556** [Azure/karpenter#55]
### What karpenter features are relevant?

AKS network plugin

### How should the docs be improved?

Clarify if karpenter on AKS use Azure network plugin instead of Cilium ? Our existing clusters are all configured to use Azure network plugin. This cannot be modified without re-creating the cluster

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ben5556** [comment]
@tallaxes @Bryce-Soghigian can you please confirm ? This should be a quick one for you guys

**Comment by tallaxes** [comment]
Currently the provider only supports (and is tested with) Azure Overlay with Cilium dataplane (`--network-plugin azure --network-plugin-mode overlay --network-dataplane cilium`).

**Comment by ben5556** [comment]
Thanks @tallaxes. Closing this

**Comment by monotek** [comment]
As Cilium is not the default in AKS i wonder if it's a commonly used network plugin among AKS users at all?
Imho this choice realy limits the Karpenter user base to a few AKS users?

**Comment by munjalpatel** [comment]
I agree. We have custom `Cilium` setup on AKS with custom config using BYOCNI (`network-plugin=none`). Not sure if we would be able to use `Karpenter` successfully. Would really like to use it though.

**Comment by monotek** [comment]
Why is the used network plugin a dependency for the autoscaling at all?

**Comment by Bryce-Soghigian** [comment]
Karpenter bootstraps nodes. In node bootstrapping we also pass certain labels and binaries, and configure network interfaces to be compatible with the various CNIs. 

Since karpenter is bootstrapping nodes itself it has to deal with some of these dependencies.

**Comment by Bryce-Soghigian** [comment]
I am working on support for Azure CNI Without Overlay and Azure CNI + Overlay right now.

**Comment by monotek** [comment]
Will Kubenet be supported too?
We currently have some clusters, which can't be migrated to Overlay :/

**Comment by assaftir** [comment]
Any update on this one? @Bryce-Soghigian

**Comment by munjalpatel** [comment]
@Bryce-Soghigian can we now use Karpenter with AKS + Cilium BYOCNI?

**Comment by Bryce-Soghigian** [comment]
@avi1512  have you tried managed karpenter? Managed karpenter has a better testing matrix to ensure it works, and those tests are passing for managed karpenter.


Note that we prioritize solving bugs for the managed addon, but I can take a look at self hosted and see whats wrong.  


CC: @matthchr can we think about a way to run cluster create scenarios in self hosted to test the self hosted configurations too?

**Comment by Bryce-Soghigian** [comment]
@munjalpatel  I tested BYO CNI With cilium and it seems to work for the managed addon

**Comment by avi1512** [comment]
> [@avi1512](https://github.com/avi1512) have you tried managed karpenter? Managed karpenter has a better testing matrix to ensure it works, and those tests are passing for managed karpenter.
> 
> Note that we prioritize solving bugs for the managed addon, but I can take a look at self hosted and see whats wrong.
> 
> CC: [@matthchr](https://github.com/matthchr) can we think about a way to run cluster create scenarios in self hosted to test the self hosted configurations too?

@Bryce-Soghigian , Initially, we tried using the managed Karpenter setup, where only the Karpenter CRDs were installed in the cluster via Helm charts as part of the Azure add-on. However, I do not see any Karpenter controller pods running in the cluster. It appears that the Karpenter add-on is being deployed through Helm, but the Helm release revision keeps changing. Additionally, there are no kubelet events related to Karpenter.

It seems that the Helm chart installation is either stuck or continuously retrying without completing successfully. 

![Image](https://github.com/user-attachments/assets/ad8bb53d-1123-45c0-872d-6bf273f387db)

**Comment by Bryce-Soghigian** [comment]
@karpenter pods are hosted in the managed control plane so they arent on your overlay cluster.

**Comment by avi1512** [comment]
Got it,  So the Karpenter controller pod runs on the Kubernetes control plane. However, I'm still unsure why the Helm release revision for Karpenter keeps changing. I'll try testing again using Node Auto Provisioning (NAP) mode to see if that makes a difference.

**Comment by avi1512** [comment]
@matthchr @Bryce-Soghigian , Could you please confirm if frequent changes to the Helm release could cause any issues?
Also, is it recommended and safe to use NAP (Node Auto Provisioning) mode in a production environment?
