### ISSUE TITLE
Race condition with Makefile-az.mk script + Az CLI + ACR + skaffold

### ISSUE THREAD

**Issue by KenKilty** [Azure/karpenter#57]
### Is an existing page relevant?

https://github.com/Azure/karpenter/blob/main/Makefile-az.mk

### What karpenter features are relevant?

There is an intermittent race condition with the Makefile-az.mk for initial create of resources for the Azure Karpenter quick start resulting in a failure due to the inability to find the previously created ACR resource when 'skaffold config set default-repo $(AZURE_ACR_NAME).azurecr.io/karpenter' is invoked . Waiting and re-running the script will allow normal operation to continue. A check for the existence of the ACR from a GET call may be necessary prior to the skaffold call.

``az login
az account set --subscription 00000000-0000-0000-0000-000000000000
az group create --name karpenter --location eastus -o none 
az acr create --name karpenter --resource-group karpenter-rg --sku Basic --admin-enabled -o none
az acr login  --name karpenter
Login Succeeded
az aks create  --name karpenter --resource-group karpenter-rg --attach-acr karpenter \
              --enable-managed-identity --node-count 3 --generate-ssh-keys --tags owner=karpenter -o none --network-dataplane cilium --network-plugin azure --network-plugin-mode overlay
az aks get-credentials --name karpenter --resource-group karpenter-rg --overwrite-existing
skaffold config set default-repo $(AZURE_ACR_NAME).azurecr.io/karpenter
(ResourceNotFound) The Resource 'Microsoft.ContainerService/managedClusters/karpenter' under resource group 'karpenter-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.ContainerService/managedClusters/karpenter' under resource group 'karpenter-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
make: *** [az-mkaks-cilium] Error 3

### How should the docs be improved?

Add check for the existence of the ACR from a GET call prior to the skaffold call 'skaffold config set default-repo $(AZURE_ACR_NAME).azurecr.io/karpenter' in the file linked to the issue above.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
The ResourceNotFound error seems to be unrelated to ACR: `acr login` is successful, `skaffold config set` is just a configuration change (and should not access the resource), the error is referring to cluster and not ACR.

It is more likely that it is coming from the next step, `make az-perm`, which uses `az aks show`.

I don't see an obvious reason why, but one thing that stands out is that the resource group created is called `karpenter`, but resource group used everywhere is `karpenter-rg`. May be related to the problem. Could you please check your configuration?

**Comment by KenKilty** [comment]
@tallaxes I redacted information from the actual names and the naming difference is a text find and replace failure on my part and so likely a red herring - my apologies for the confusion. I cannot consistently reproduce this issue despite efforts to do so.

Please close the issue and thank you.
