### ISSUE TITLE
Feature: AKS Karpenter Az CLI + Terraform deployment support

### ISSUE THREAD

**Issue by KenKilty** [Azure/karpenter#63]
### Tell us about your request

Request 1: Provide a means to deploy Karpenter via the Azure CLI in the manner that is supported for Keda. For example:

`az aks create -g MyResourceGroup -n MyManagedCluster --enable-karpenter`

Request 2: Provide a means to deploy Karpenter via Terraform either via the AKS Terraform provider or via add-on specification and means to configure requirements via values.yaml (vm family, cpu, location, etc). For example:

```
{
<snip>
resource "azurerm_kubernetes_cluster" "aks_app" {
  name                = var.cluster_name
  location            = azurerm_resource_group.rg_keda.location
  resource_group_name = azurerm_resource_group.rg_keda.name
  dns_prefix          = var.dns_prefix

  <snip >

# Helm and Karpenter installation

provider "helm" {
  version = ">= 0.7"

  kubernetes {
    host                   = azurerm_kubernetes_cluster.aks_app.kube_config.0.host
    client_certificate     = base64decode(azurerm_kubernetes_cluster.aks_app.kube_config.0.client_certificate)
    client_key             = base64decode(azurerm_kubernetes_cluster.aks_app.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.aks_app.kube_config.0.cluster_ca_certificate)
    load_config_file       = false
  }
}

resource "helm_release" "karpenter" {
  name       = "karpenter"
  repository = "https://karpenter-aks.github.io/charts"
  chart      = "karpenter"
  namespace  = "default"

values = [
    file("${path.module}/karpenter-values.yaml")
  ]

  devel = "true"

  set {
    name  = "logLevel"
    value = "debug"
  }
}
```

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Simplify deployment for Karpenter on AKS using Microsoft maintained (curated) images for Karpenter for AKS. Avoid the need for a local build and container push. Simplify the configuration of requirements for Karpenter (configuration).

### Are you currently working around this issue?

Yes. Via forking and modification of the Karpenter provider for AKS Github repository.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by philwelz** [comment]
You can do it now via `az aks create --name karpuktest --resource-group karpuk --node-provisioning-mode Auto --network-plugin azure --network-plugin-mode overlay --network-dataplane cilium` as described [here](https://learn.microsoft.com/en-gb/azure/aks/node-autoprovision?tabs=azure-cli).

As it is preview i think we have to wait little for Terraform support.

**Comment by KenKilty** [comment]
Thank you @philwelz!
