### ISSUE TITLE
Missing installation of yq on Codespace's Dockerfile

### ISSUE THREAD

**Issue by ldardick** [Azure/karpenter#82]
### Version

N/A, doesn't apply

### Expected Behavior

Running `make az-all` should succeed when ran from Codespaces as explained in the docs

### Actual Behavior

Task fails because `yq` is not installed and it's used in the makefile

### Steps to Reproduce the Problem

- Create a Codespace from `main`
- Set the home subscription as defined in the docs
- Run `make az-all`
- The process will fail after creating the AKS cluster 

### Resource Specs and Logs

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
`yq` is installed by `hack/toolchain.sh` which is called from `postCreateCommand`. Is it possible you tried running `make az-all` before `make toolchain` finished? You should observe it running in the terminal.

https://github.com/Azure/karpenter/blob/3bb0a651f9f08bdb41c0cdea419a37bb7dd90024/hack/toolchain.sh#L16

https://github.com/Azure/karpenter/blob/3bb0a651f9f08bdb41c0cdea419a37bb7dd90024/.devcontainer/devcontainer.json#L47-L49

**Comment by tallaxes** [comment]
Closing. @ldardick let us know if `make toolchain` does not resolve the issue.
